#!/bin/bash

####################################################################################
# Return exit code 0 if connected
####################################################################################

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

netstat -pant | grep -q "ESTABLISHED.*python"
#!/bin/bash

####################################################################################
# Return exit code 0 if connected
####################################################################################

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

netstat -pant | grep -q "ESTABLISHED.*python"

